### PR TITLE
Remove duplicate install instructions & update README

### PR DESCRIPTION
**Pull request by robphoenix**
I ended up being a bit liberal with my changes to the README, do let me know if you want anything done differently. I lifted some of this from the xgo readme.

### CODE REVIEW

**Comment by ryanplusplus** [comment]
I was going to say that some of this is (probably) covered in https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md, but that thing is such a beast that I like having the simple overview here and letting contributors check out the actual contributing guide for everything else.

**Comment by ryanplusplus** [comment]
Changes look great. Are you interested in being a maintainer for the Lua track? I'm the only active maintainer right now and I have a 2 week old baby so any help would be appreciated 😃 .

**Comment by robphoenix** [comment]
Thanks :smile: Yeah, I'd love to help out. I've only just started learning Lua but this would be a great way to learn, if you don't mind me deferring to you when I'm not sure.

Congratulations btw, I've got a preschooler and a toddler so I can understand how utterly exhausted you probably are right now!

**Comment by ryanplusplus** [comment]
Excellent, I'll ask Katrina to make you a maintainer.

**Comment by robphoenix** [comment]
:+1:

**Comment by ryanplusplus** [comment]
@robphoenix all done!

**Pull request merged**
