### PR TITLE
accumulate: deprecate

### PR DESCRIPTION
**Pull request by robphoenix**
see https://github.com/exercism/x-common/issues/553#issuecomment-279275406

### CODE REVIEW

**Comment by robphoenix** [comment]
@ryanplusplus If this is getting merged let me know if you also want to remove the accumulate directory from exercises, and I can include that in this commit.

**Comment by ryanplusplus** [comment]
Yeah, can you remove the actual exercise?

**Comment by robphoenix** [comment]
done :white_check_mark:

**Comment by ryanplusplus** [comment]
Thanks!

**Pull request merged**
