### PR TITLE
Added Atbash cipher

### PR DESCRIPTION
**Pull request by ryanplusplus**

### CODE REVIEW

**Comment by kytrinyx** [comment]
The failure here is some custom glue code that I put together to lint at the project level: https://github.com/exercism/configlet/blob/master/README.md

Let me know if anything is confusing.

**Comment by ryanplusplus** [comment]
Got it, had the exercise name wrong in `config.json` ("atbash_cipher" instead of "atbash-cipher"). CI wins again.

**Comment by kytrinyx** [comment]
Yay, CI!

**Comment by kytrinyx** [comment]
Would you mind squashing the commits on this one? It seems like they all belong together.

**Comment by ryanplusplus** [comment]
Squashed

**Pull request merged**
