### PR TITLE
Added bank account exercise

### PR DESCRIPTION
**Pull request by ryanplusplus**
The multi-thread/context access portion of this problem is meaningless in Lua, but this problem is good practice for assertions/errors and as practice with OO in Lua.

### CODE REVIEW

**Comment by aarti** [comment]
This looks great. Agreed on the multi-thread being meaningless for lua. It would be great if we could add a specific readme just for this exercise and point to relevant documentation. http://lua-users.org/wiki/ThreadsTutorial

**Comment by kytrinyx** [comment]
We've been talking about how to do language-specific stuff for the README here: https://github.com/exercism/x-api/issues/44 I think if we can just decide on a file name, someone would probably be willing to pick this up as part of 24pullrequests.

Maybe `HINTS.md`?

**Comment by aarti** [comment]
Hints.md sounds like a good name

**Comment by ryanplusplus** [comment]
What's the verdict on this? Good to go or do we want to wait on `HINTS.md`?

**Comment by kytrinyx** [comment]
Good question. Let's merge this in and then when the `HINTS.md` thing gets implemented, we can add it to the exercise.

**Pull request merged**
