### PR TITLE
Added the track icon

### LINKED ISSUE #151: Copy track icon into language track repository
Right now all of the icons used for the language tracks (which can be seen at http://exercism.io/languages) are stored in the exercism/exercism.io repository in `public/img/tracks/`. It would make a lot more sense to keep these images along with all of the other language-specific stuff in each individual language track repository.

There's a pull request that is adding support for serving up the track icon from the x-api, which deals with language-specific stuff.

In order to support this change, each track will need to

- create a directory named `img/` at the root of this repository if it doesn't already exist, then
- find the correct icon in https://github.com/exercism/exercism.io/tree/master/public/img/tracks, and
- stick it in the `img/` directory, and importantly
- **name the image `icon.png`**

In other words, at the end of it you should have the following file:

```
./img/icon.png
```

See https://github.com/exercism/exercism.io/issues/2925 for more details.

### PR DESCRIPTION
**Pull request by ryanplusplus**
Closes #151

### CODE REVIEW

**Comment by ryanplusplus** [comment]
@kytrinyx apparently `/bin/configlet` is not pleased about an `img` directory at the root because `img` is not in `config.json`. Please see https://github.com/exercism/configlet/pull/5.

**Comment by kytrinyx** [comment]
OK, I've released a new version of configlet. (Thanks for fixing that!) I'm going to try kicking off the build again to see if that fixes it.

**Comment by kytrinyx** [comment]
Darn. I can't find the "re-run" button on Travis for the PR. Would you mind doing a push -f to this branch to see if that kicks it off?

**Comment by kytrinyx** [comment]
Ooooh! It's a legit failure!

```
Failure → ./grains_spec.lua @ 28
grains square 64
./grains_spec.lua:29: Expected objects to be equal.
Passed in:
(number) -9223372036854775808
Expected:
(number) 9223372036854775808.0
stack traceback:
	./grains_spec.lua:29: in function <./grains_spec.lua:28>
Failure → ./grains_spec.lua @ 32
grains total
./grains_spec.lua:33: Expected objects to be equal.
Passed in:
(number) -1
Expected:
(number) 18446744073709551616.0
stack traceback:
	./grains_spec.lua:33: in function <./grains_spec.lua:32>
```

**Comment by ryanplusplus** [comment]
Yeah... might be due to Lua 5.3.3. I'm going to go ahead and merge this and create an issue to fix that.

**Pull request merged**
