### PR TITLE
Added accumulate exercise

### PR DESCRIPTION
**Pull request by ryanplusplus**
Pretty simple, feedback welcome

### CODE REVIEW

**Comment by kytrinyx** [comment]
Nice, this is a great first exercise, I think.

**Comment by kytrinyx** [comment]
One thing... we've been talking about potentially deprecating this exercise and only having the "list operations" exercise, but no final decision has been made. Just something to keep an eye on.

**Comment by ryanplusplus** [comment]
@kytrinyx does the order in `config.json` determine the order of exercises for the track? If so, I'll keep that in mind. I've just been inserting new exercises in places that I thought were least likely to cause conflicts with my other pull requests :)

**Comment by kytrinyx** [comment]
Haha, that's as good a reason as any, but yes; the order listed in the config is the order that people will get them served up.

Mostly it doesn't matter, but occasionally there are problems that are complicated enough that we want to put them farther towards the end, or there are a few that are similar enough to each other that we don't want them clumped together (several nursery rhymes / children's songs, for example. Different algorithms, but lots of heavy text-based solutions.)

**Pull request merged**
