### PR TITLE
Moved exercises under exercises/

### LINKED ISSUE #99: Move exercises to subdirectory
The problems api (x-api) now supports having exercises collected in a subdirectory
named `exercises`.

That is to say that instead of having a mix of `bin`, `docs`, and individual exercises,
we can have `bin`, `docs`, and `exercises` in the root of the repository, and all
the exercises collected in a subdirectory.

In other words, instead of this:

```
x{TRACK_ID}/
├── LICENSE
├── README.md
├── bin
│   └── fetch-configlet
├── bowling
│   ├── bowling_test.ext
│   └── example.ext
├── clock
│   ├── clock_test.ext
│   └── example.ext
├── config.json
└── docs
│   ├── ABOUT.md
│   └── img
... etc
```

we can have something like this:

```
x{TRACK_ID}/
├── LICENSE
├── README.md
├── bin
│   └── fetch-configlet
├── config.json
├── docs
│   ├── ABOUT.md
│   └── img
├── exercises
│   ├── bowling
│   │   ├── bowling_test.ext
│   │   └── example.ext
│   └── clock
│       ├── clock_test.ext
│       └── example.ext
... etc
```

This has already been deployed to production, so it's safe to make this change whenever you have time.

### PR DESCRIPTION
**Pull request by ryanplusplus**
Closes #99

### CODE REVIEW

**Comment by ryanplusplus** [comment]
This will fail until the configlet is updated. I'll re-trigger Travis when that is ready.

**Comment by kytrinyx** [comment]
Should be good to go now.

**Comment by ryanplusplus** [comment]
Travis is happy and there isn't much to review. Merging...

**Comment by kytrinyx** [comment]
sweet!

**Pull request merged**
