### PR TITLE
Removed gray area test in Triangle exercise

### LINKED ISSUE #107: triangle: incorrect test in some tracks
Please check if there's a test that states that a triangle with sides 2, 4, 2 is invalid. The triangle inequality states that for any triangle, the sum of the lengths of any two sides must be greater than or equal to the length of the remaining side. If this doesn't affect this track, go ahead and just close the issue.

### PR DESCRIPTION
**Pull request by ryanplusplus**
Fixes #107

### CODE REVIEW

**Comment by kytrinyx** [comment]
+1 - thanks!

**Comment by ryanplusplus** [comment]
Per #107 I think we need to hold off until there's consensus about the right solution

**Comment by kytrinyx** [comment]
Yeah, good point. So sorry about wording it unclearly, and not starting the discussion in x-common first!

**Comment by ryanplusplus** [comment]
Updated to simply remove the offending test per the discussion in exercism/xerlang#85

**Comment by kytrinyx** [comment]
Yeah, this is the right way to go.

**Pull request merged**
