### PR TITLE
LEARNING.md: fix broken link

### PR DESCRIPTION
**Pull request by robphoenix**

### CODE REVIEW

**Comment by robphoenix** [comment]
Ah, vim autoformats my markdown files. I can revert this if you'd prefer?

**Comment by robphoenix** [comment]
Sorry, I don't know why these changes have broken the minesweeper tests, they still pass locally ??

**Comment by ryanplusplus** [comment]
@robphoenix I think the minesweeper issue is on our side: #187

**Comment by ryanplusplus** [comment]
Don't worry about the auto-formatting, I changed the part that bothers me :)

**Pull request merged**
