### PR TITLE
Added alphametics problem

### PR DESCRIPTION
**Pull request by ryanplusplus**
This problem was very interesting because:

1. It's tougher than most problems on Exercism
1. it shows how powerful `dostring` (ie: eval) is
1. It has legitimate uses for co-routines
1. It is computationally intense enough that optimizations and profiling are important
1. My solution works, but I'm sure someone else will have something better :)

I hope to see this problem on more tracks soon

### CODE REVIEW

**Comment by kytrinyx** [comment]
This looks great, thanks. I'm always excited to see more exercises added!

I'm going to leave it to @aarti to merge, since I don't know Lua.

**Comment by ryanplusplus** [comment]
@kytrinyx thanks!

**Comment by aarti** [comment]
Sorry just got back from holidays, looking at these PR's now.

**Comment by ryanplusplus** [comment]
Thanks @aarti!

**Pull request merged**
